"""Wire-format tests for the package signature document (B9/G9)."""

import base64

import pytest
from python_hub_contracts import (
    SIGNATURE_ALGORITHM,
    SignatureDocumentError,
    key_fingerprint,
    normalize_public_key,
    parse_signature_document,
    render_signature_document,
    signature_message,
)

PUBLIC_KEY = bytes(range(32))
SIGNATURE = bytes((i * 7 + 3) % 256 for i in range(64))
PACKAGE_SHA256 = "ab" * 32


def test_signature_message_is_domain_separated_and_digest_bound() -> None:
    """The signed bytes must never collide with raw digests in other protocols."""
    message = signature_message(PACKAGE_SHA256)

    assert message == b"hub-plugin-package:v1:" + PACKAGE_SHA256.encode("ascii")
    assert message.startswith(b"hub-plugin-package:v1:")


def test_signature_message_rejects_non_hex_digests() -> None:
    with pytest.raises(SignatureDocumentError):
        signature_message("zz" * 32)
    with pytest.raises(SignatureDocumentError):
        signature_message("ab" * 31)


def test_key_fingerprint_is_16_hex_characters() -> None:
    assert key_fingerprint(PUBLIC_KEY) == key_fingerprint(PUBLIC_KEY)
    assert len(key_fingerprint(PUBLIC_KEY)) == 16
    assert key_fingerprint(PUBLIC_KEY) != key_fingerprint(bytes(range(1, 33)))


def test_key_fingerprint_rejects_wrong_length() -> None:
    with pytest.raises(SignatureDocumentError):
        key_fingerprint(b"short")


def test_normalize_public_key_round_trips_to_canonical_base64() -> None:
    canonical = base64.b64encode(PUBLIC_KEY).decode("ascii")

    assert normalize_public_key(canonical) == canonical


def test_normalize_public_key_rejects_invalid_entries() -> None:
    with pytest.raises(SignatureDocumentError):
        normalize_public_key("not base64!!")
    with pytest.raises(SignatureDocumentError):
        normalize_public_key(base64.b64encode(b"short").decode("ascii"))


def test_render_and_parse_round_trip() -> None:
    document = render_signature_document(PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE)

    parsed = parse_signature_document(document.encode("utf-8"))

    assert parsed.algorithm == SIGNATURE_ALGORITHM
    assert parsed.signature == SIGNATURE
    assert parsed.key_fingerprint == key_fingerprint(PUBLIC_KEY)
    assert parsed.package_sha256 == PACKAGE_SHA256


def test_parse_ignores_comments_blank_lines_and_unknown_fields() -> None:
    document = render_signature_document(PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE)
    decorated = (
        "# generated by hub-plugin sign\n"
        "\n"
        "trusted comment: future field\n"
        + document
    )

    parsed = parse_signature_document(decorated.encode("utf-8"))

    assert parsed.signature == SIGNATURE


def test_parse_rejects_unknown_algorithm() -> None:
    document = render_signature_document(PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE).replace(
        "algorithm: ed25519", "algorithm: rsa2048"
    )

    with pytest.raises(SignatureDocumentError, match="algorithm"):
        parse_signature_document(document.encode("utf-8"))


def test_parse_rejects_duplicate_fields() -> None:
    document = (
        render_signature_document(PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE)
        + "algorithm: ed25519\n"
    )

    with pytest.raises(SignatureDocumentError, match="algorithm"):
        parse_signature_document(document.encode("utf-8"))


def test_parse_rejects_missing_signature_and_non_key_value_lines() -> None:
    with pytest.raises(SignatureDocumentError):
        parse_signature_document(b"algorithm: ed25519\n")
    with pytest.raises(SignatureDocumentError):
        parse_signature_document(b"just some text\n")


def test_parse_rejects_bad_base64_or_wrong_length_signature() -> None:
    bad_base64 = "algorithm: ed25519\nsignature: not-base64!!\n"
    with pytest.raises(SignatureDocumentError, match="base64"):
        parse_signature_document(bad_base64.encode("utf-8"))

    wrong_length = (
        f"algorithm: ed25519\nsignature: {base64.b64encode(b'short').decode('ascii')}\n"
    )
    with pytest.raises(SignatureDocumentError, match="64"):
        parse_signature_document(wrong_length.encode("utf-8"))


def test_parse_rejects_non_utf8_and_bad_advisory_fields() -> None:
    with pytest.raises(SignatureDocumentError, match="UTF-8"):
        parse_signature_document(b"\xff\xfe")

    bad_fingerprint = render_signature_document(
        PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE
    ).replace(key_fingerprint(PUBLIC_KEY), "nothex")
    with pytest.raises(SignatureDocumentError, match="key_fingerprint"):
        parse_signature_document(bad_fingerprint.encode("utf-8"))

    bad_digest = render_signature_document(PUBLIC_KEY, PACKAGE_SHA256, SIGNATURE).replace(
        PACKAGE_SHA256, "AB" * 32
    )
    with pytest.raises(SignatureDocumentError, match="package_sha256"):
        parse_signature_document(bad_digest.encode("utf-8"))
