"""Public contracts for Python Service Hub."""

from .build_manifest import PackagedRuntime, PluginBuildManifest, TargetPlatform
from .common import (
    PluginId,
    RelativeProtocolPath,
    SemanticVersion,
    StrictContractModel,
    normalize_arch,
    normalize_os,
)
from .job_protocol import (
    FileRole,
    JobError,
    JobResult,
    JobRuntimeSpec,
    JobStatus,
    RuntimeDirectories,
    RuntimeExecution,
    RuntimeInputFile,
    RuntimeInputFiles,
    RuntimeInputValue,
    RuntimeJob,
    RuntimeOutputFile,
    RuntimePlugin,
)
from .plugin_manifest import (
    EntryPointSpec,
    EnvironmentDeclaration,
    EnvironmentVariablesSpec,
    ExecutionSpec,
    HealthcheckSpec,
    InputSpec,
    OutputSpec,
    ParameterSpec,
    PluginInfo,
    PluginManifest,
    PythonSpec,
    RuntimeSpec,
    SdkSpec,
)
from .runner_events import (
    RUNNER_EVENT_PREFIX,
    LogEvent,
    LogLevel,
    ProgressEvent,
    RunnerEvent,
    RunnerEventParseError,
    parse_runner_line,
)
from .yaml_io import load_plugin_manifest

__version__ = "0.1.0"

__all__ = [
    "RUNNER_EVENT_PREFIX",
    "EntryPointSpec",
    "EnvironmentDeclaration",
    "EnvironmentVariablesSpec",
    "ExecutionSpec",
    "FileRole",
    "HealthcheckSpec",
    "InputSpec",
    "JobError",
    "JobResult",
    "JobRuntimeSpec",
    "JobStatus",
    "LogEvent",
    "LogLevel",
    "OutputSpec",
    "PackagedRuntime",
    "ParameterSpec",
    "PluginBuildManifest",
    "PluginId",
    "PluginInfo",
    "PluginManifest",
    "ProgressEvent",
    "PythonSpec",
    "RelativeProtocolPath",
    "RunnerEvent",
    "RunnerEventParseError",
    "RuntimeDirectories",
    "RuntimeExecution",
    "RuntimeInputFile",
    "RuntimeInputFiles",
    "RuntimeInputValue",
    "RuntimeJob",
    "RuntimeOutputFile",
    "RuntimePlugin",
    "RuntimeSpec",
    "SdkSpec",
    "SemanticVersion",
    "StrictContractModel",
    "TargetPlatform",
    "load_plugin_manifest",
    "normalize_arch",
    "normalize_os",
    "parse_runner_line",
]
